### PR TITLE
Added a message box when HLT stops execution.

### LINKED ISSUE #125: Request for notification on encountering HLT
When the halt machine instruction (0xF4) is encountered, the application should notify the user that the execution has halted. Preferably done as a popup window or output to stdio.

**Steps to reproduce:**
1. Load executable Virgo object file into simulator.
2. Clicked run
3. No feedback application has finished execution, other than output to (internal) terminal.

While the documented behavior for HLT on x86 is to deep idle the processor until an external interrupt is received, Libra should still notify the user that the simulator has entered said state.

### PR DESCRIPTION
**Pull request by rdnelson**
Fixes #125

### CODE REVIEW

**Comment by rdnelson** [comment]
@hasithvm want to verify this one?

**Comment by hasithvm** [comment]
You broke it.
(there's a compiling issue). @DarrenStahl ?

``` bash
hasith@mint-desktop:~/development/Libra/src$ make
g++ -c -m64 -pipe -g -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o Jcc.o opcodes/Jcc.cpp
opcodes/Jcc.cpp: In member function ‘virtual int Jcc::Execute(Processor*)’:
opcodes/Jcc.cpp:177:15: error: ‘numeric_limits’ is not a member of ‘std’
opcodes/Jcc.cpp:177:35: error: expected primary-expression before ‘int’
opcodes/Jcc.cpp:177:35: error: expected ‘;’ before ‘int’
make: *** [Jcc.o] Error 1
```

**Comment by DarrenStahl** [comment]
Dunno why that would break for you, but neither of us... Fix incoming.

**Comment by rdnelson** [comment]
That's not on this one. That's on the one I just merged. It should be fixed now. It's a required header for linux, but included by default on windows. That's why I didn't catch it, I'm on a windows box today.

**Comment by hasithvm** [comment]
Looks good to me.

**Pull request merged**
