### PR TITLE
Instruction view now shows listings

### PR DESCRIPTION
**Pull request by rdnelson**
This option is toggleable

Fixes #132

### CODE REVIEW

**Comment by rdnelson** [comment]
@DarrenStahl Please verify that the listing view doesn't break anything, and looks ok on the lab code. It can be toggled in the new options menu.

**Comment by DarrenStahl** [comment]
Will test more later tonight, but toggling back on does not appear to work. Once it is off, it does not come back.

**Comment by rdnelson** [comment]
@DarrenStahl That issue should be fixed now.

**Comment by DarrenStahl** [comment]
Looks good

**Pull request merged**
